[tool.poetry]
name = "kubedownscaler"
version = "0.1.0"
description = "Scale down and restore deployments and statefulsets"
authors = ["Jonathan Gazeley <me@jonathangazeley.com>"]

[tool.poetry.dependencies]
python = "^3.10"
kubernetes = "^19.15.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
